# Generated by Django 4.2 on 2023-06-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatmessage_attached_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
