# Generated by Django 4.2 on 2023-06-23 04:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_thread_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
