# Generated by Django 4.2 on 2023-05-05 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('profile_img', models.ImageField(upload_to='profile_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='post_images/')),
                ('phone_number', models.CharField(max_length=30)),
                ('more_info', models.TextField(blank=True, null=True)),
                ('price', models.CharField(max_length=20)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('liked', models.PositiveBigIntegerField(default=0)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.city')),
                ('post_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.basicuser')),
            ],
        ),
        migrations.CreateModel(
            name='CityGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cities', models.ManyToManyField(to='main.city')),
            ],
        ),
        migrations.AddField(
            model_name='basicuser',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.city'),
        ),
        migrations.AddField(
            model_name='basicuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
