# Generated by Django 4.2 on 2023-05-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
