# Generated by Django 4.2 on 2023-05-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_post_liked_alter_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='phone_number',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='basicuser',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='media/post_images/'),
        ),
    ]
