# Generated by Django 4.2 on 2023-06-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_basicuser_profile_img_alter_category_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
