# Generated by Django 4.2 on 2023-06-18 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_location_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 6, 18, 12, 41, 31, 441177, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
