# Generated by Django 4.2 on 2023-06-18 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicuser',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.location'),
        ),
        migrations.AlterField(
            model_name='basicuser',
            name='city',
            field=models.ForeignKey(on_delete=models.SET('other'), to='main.city'),
        ),
    ]
