# Generated by Django 4.2 on 2023-06-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_basicuser_location_alter_basicuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
