# Generated by Django 4.2 on 2023-06-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='images',
            field=models.ManyToManyField(to='main.image'),
        ),
    ]
