# Generated by Django 4.2 on 2023-06-20 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_comment_basicuser_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city'),
        ),
    ]
