# Generated by Django 4.2 on 2023-06-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_basicuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='possibilities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
