# Generated by Django 4.2 on 2023-06-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_testdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_blocked',
            field=models.BooleanField(default=True),
        ),
    ]
