# Generated by Django 4.2 on 2023-06-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='top_attempts',
            field=models.IntegerField(default=1),
        ),
    ]
