# Generated by Django 4.2 on 2023-06-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_post_top_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='top_attempts',
        ),
        migrations.AddField(
            model_name='basicuser',
            name='top_attempts',
            field=models.IntegerField(default=1),
        ),
    ]
